version: '3.4'

services:
  postg:
    image: postgres:9.5
    restart: always
    environment: 
        POSTGRES_PASSWORD: Welcome1**
    ports:
        - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on: 
        - postg
        - rabbitmq
    links:
        - postg:db